### ISSUE TITLE
Add a contact page

### ISSUE THREAD

**Issue by dogoepp** [resibots/resibots.github.io#2]
Would it make sense to add a contact page with information about how to reach us (or rather JB) ? Or perhaps could an e-mail address on the _team_ page be enough.

@jbmouret your opinion ?

**Comment by jbmouret** [comment]
A contact page is a good idea. (with also the postal address, etc.)

� JB
On 08 Jan 2016, at 15:10, Dorian Goepp notifications@github.com wrote:

> Would it make sense to add a contact page with information about how to reach us (or rather JB) ? Or perhaps could an e-mail address on the team page be enough.
> 
> @jbmouret your opinion ?
> 
> �
> Reply to this email directly or view it on GitHub.

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by dogoepp** [comment]
solved by #4
