### ISSUE TITLE
Update pictures of Omnigrasper

### ISSUE THREAD

**Issue by dogoepp** [resibots/resibots.github.io#5]
Since we now have an arm on the robot, we might want to update the related picture, wouldn't we ?

**Comment by jbmouret** [comment]
We want!

**Comment by costashatz** [comment]
+1 from me too!

**Comment by dogoepp** [comment]
Great !

I guess we can use JB's camera. I'll be there on Tuesday to do it, if 
noone felt the urge to take pictures in the mean time :')

**Comment by jbmouret** [comment]
[image: 20160208-IMG_9078.jpg]

**Comment by costashatz** [comment]
> [image: 20160208-IMG_9078.jpg]

I cannot see the image.. You should upload it from the github website, not your email.

**Comment by dogoepp** [comment]
Solved by #6
