### ISSUE TITLE
Link to creadapt.net

### ISSUE THREAD

**Issue by dogoepp** [resibots/resibots.github.io#7]
On the [Lab & Robots (photos)](http://www.resibots.eu/photos.html#creadapt-robot-wheel-leg-hybrid) page, in the [creadapt](http://www.resibots.eu/photos.html#creadapt-robot-wheel-leg-hybrid) section, there is a link to http://www.creadapt.net which redirects to resibots.eu.

What should be done of it ?

@jbmouret

**Comment by jbmouret** [comment]
Point to this:
https://members.loria.fr/JBMouret/creadapt.html
